name: 'Build + Publish NuGet Package'

on:
  # Run workflow file whenever a pull request is opened, or a commit is pushed to it.
  pull_request:
    types: [opened, synchronize]

  # Run workflow file on commits to the main branch.
  push:
    branches:
      - master
      - main

env:
  DOTNET_NOLOGO: true

jobs:
  # Build NuGet packages
  build:
    if: "!contains(toJSON(github.event.commits.*.message), '[SKIP BUILD]')"

    runs-on: 'ubuntu-latest'

    env:
      # Combining the PR number, the run number, and the run attempt generates a unique
      # version every time to avoid attempting to upload duplicate versions.
      # The run number and run attempts should always be higher than the previous run.
      VersionSuffix: ${{ github.event.pull_request.number && format('pr-{0}-{1}-{2}-preview', github.event.pull_request.number, github.run_number, github.run_attempt) || '' }}
      SOLUTION_FILE_NAME: './Template.sln'

    steps:
      # Setup
      - name: 'Clone Repository'
        uses: actions/checkout@v3

      - name: 'Setup .NET'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      # Build
      - name: 'NuGet Restore'
        run: >-
          dotnet restore
          ${{ env.SOLUTION_FILE_NAME }}
      - name: 'Build Assemblies'
        run: >-
          dotnet build
          ${{ env.SOLUTION_FILE_NAME }}
          --no-restore
          -c Release
      - name: 'Run Unit Tests'
        run: >-
          dotnet test
          ${{ env.SOLUTION_FILE_NAME }}
          --no-build
          --no-restore
          -c Release
